### ISSUE TITLE
Optional Hint Feature for Passphareses

### ISSUE THREAD

**Issue by aligungr** [Proje481/Signal-Android#1]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------
### Feature Description
Currently the application does not permit users to specify a hint for their passphrases (or passwords) to make them more secure. I do not believe that this would be an actual security problem as long as users are aware of what they are doing. Because of that we should provide an optional hint feature for passwords.

### Some Important Points
- This feature must be optional, we cannot force users to use this feature.
- There should be an expression in the application which indicates that using hints is not recommended and not necessary for most of the users.
- We should not let users to specify some unreasonably long or expressive hints, because this may cause other people to trivially predict user's password
- The hint text must not contain the password's itself neither fully nor partially.

**Comment by cagdasgerede** [comment]
Bunu siz mi yazdınız yoksa bir yerden kopyaladınız mı?

**Comment by aligungr** [comment]
@cagdasgerede Evet hocam ben yazdım
